### ISSUE TITLE
When using with babel, sourcemap is not generated if a file with tests has a jsx extension

### ISSUE THREAD

**Issue by aush** [ryanclark/karma-webpack#104]
Repo to reproduce: [https://github.com/aush/karma-webpack-jsx-extension-bug](https://github.com/aush/karma-webpack-jsx-extension-bug), `npm run test`

If you change an extension for the index.spec.js file to 'jsx', a resulting bundle doesn't have a link to a sourcemap `//# sourceMappingURL=index.spec.js.map` as the last line of code.

It doesn't matter if the file actually has jsx syntax, even if it has, everything works correctly except a link to a sourcemap is not present.

Source files can have any extension, it doesn't affect presence of a link to a sourcemap.

karma.conf.js:

``` javascript
const path = require('path');

module.exports = function(config) {
  config.set({
    basePath: '',
    frameworks: ['mocha'],
    reporters: ['dots'],
    singleRun: false,
    autoWatch: true,
    browsers: ['Chrome'],
    files: ['./src/**/*.spec.js*'],
    preprocessors: {
      './src/**/*.spec.js*': ['webpack']
    },
    webpack: {
      devtool: 'source-map',
      module: {
        loaders: [{
          test: /\.jsx?$/,
          loader: 'babel?presets[]=react',
          include: path.join(__dirname, 'src')
        }]
      },
      resolve: { extensions: ['', '.js', '.jsx'] }
    },
    webpackMiddleware: {
      noInfo: true
    }
  });
};
```

src/index.jsx:

``` javascript
require('react');
module.exports = function () { return <div/>; };
```

src/index.spec.js:

``` javascript
var expect = require('chai').expect;
var component = require('./index');

describe('component', function () {
  it('should test', function () { expect(component).to.be.ok; });
});
```

**Comment by awong-dev** [comment]
I'm hitting this as well. webpack somehow doesn't seem to be applying the devtools setting to .jsx in general.

**Comment by awong-dev** [comment]
https://github.com/webpack/webpack/blob/5b5775f9e2fc73fea46629f2d6a3ed7a1f8424d3/lib/SourceMapDevToolPlugin.js#L35

^^^ There's the bug.  If you add jsx to the regex, the sourcemap works.  Now...how to set options.test...

**Comment by codymikol** [comment]
Closing as this issue was solved in webpack AFAICT. I'm aggregating discussion about supporting 'source-map' over here if anyone is still interested ===> https://github.com/ryanclark/karma-webpack/issues/485
