### ISSUE TITLE
Test Runs twice

### ISSUE THREAD

**Issue by IngenieroLata** [ryanclark/karma-webpack#118]
Hello! I'm dealing with a really simple set up with **Angular 1.5**, **webpack** and **karma**. But dunno why is running the tests twice. The thing is that is happening just when I'm calling the service.

Here is the repo https://github.com/IngenieroLata/lata-simple-test-set

```
// heroService.test.js

import droidServiceModule from './index.js';

describe('droidServiceModule', () => {

    let droidService;

    beforeEach(angular.mock.module(droidServiceModule.name));

    beforeEach(inject(function($injector) {
        droidService = $injector.get('droidService');
    }));

    it('should test properly', () => {

        /*RUN TWICE*/
        // droidService.name = 'r2d2'; 
        // console.log(droidService.name);
        // console.log(droidService.speak());

        expect(true).to.be.true;

    });
});
```

I'm using `karma-webpack` with a configuration file `'./test/test_index.js';`:

```
// test_index.js

require('angular');
require('angular-mocks');

var testsContext = require.context("../app", true, /\.test$/);
testsContext.keys().forEach(testsContext);
```

Any idea why is this happening?

**Comment by IngenieroLata** [comment]
reading this comment https://github.com/nikku/karma-browserify/issues/67#issuecomment-84281528 related with this other comment https://github.com/webpack/karma-webpack/issues/44#issuecomment-133619802 
I realize that I have configured the `webpack.HotModuleReplacementPlugin` so, disabling it from `plugins` and `hot` option in the `devServer` sections in webpack.config file works sometimes for me. 

Also, I try to use `files` like this but got the same result
```
files: [
  {pattern: './spec.js', watched: false, included: true, served: true}
],

```

**Comment by lricoy** [comment]
This solution **1** from this comment worked for me: https://github.com/nikku/karma-browserify/issues/67#issuecomment-262128601

- Using ```files: [{pattern: '**/*.spec.js', watched: false}]```by @mattfysh

**Comment by codymikol** [comment]
Closing due to the age of this ticket, if you're still having issues with the current build feel free to open a new ticket with the relevant information and I'll help as best I can!
