### ISSUE TITLE
Should report bundle error when bundle failed.

### ISSUE THREAD

**Issue by holmescn** [ryanclark/karma-webpack#119]
When I switch from karma-browserify to karma-webpack, I found that if something wrong in my code, it just report file not found in the memory fs. But actually, it is because that the source code bundle failed.
My karma-webpack version is 1.7.0.

**Comment by holmescn** [comment]
To be more specific, errors only report when there is one file. If there multiple files, it will not report bundle error.

**Comment by d3viant0ne** [comment]
@holmescn - I'm going to need some sort of minimal project to repo this issue or point me toward the project you are having issues with.

**Comment by codymikol** [comment]
closing as no repro has been provided
