### ISSUE TITLE
Dealing with externals?

### ISSUE THREAD

**Issue by ghost** [ryanclark/karma-webpack#125]
My webpack section in karma.webpack.config.js looks like belowe

```
webpack: {
            cache: true,
            devtool: "inline-source-map",
            resolve: {
                 alias: {
                    "_testRoot": path.resolve(process.cwd(), "src", "__tests__"),
                    "_srcRoot": path.resolve(process.cwd(), "src", "main")
                },
                extensions: [ "", ".js" ]
            },
            module: {
                preLoaders: [
                    {
                        test: /\.js$/,
                        include: testPath,
                        exclude: /(node_modules)/,
                        loader: "babel",
                        query: {
                            cacheDirectory: true
                        }
                    },
                    {
                        test: /\.js?$/,
                        include: path.resolve(process.cwd(), "src"),
                        exclude: /(node_modules|__tests__)/,
                        loader: "babel-istanbul",
                        query: {
                            cacheDirectory: true
                        }
                    }
                ],
                loaders: [
                    {
                        test: /\.js$/,
                        include: path.resolve(process.cwd(), "src"),
                        exclude: /(node_modules|__tests__)/,
                        loader: "babel",
                        query: {
                            cacheDirectory: true
                        }
                    }
                ]
            },
              externals:{
                ComponentStyle:'ComponentStyle'
              }
          }
```

And I have ComponentStyle defined as a dependency in one of my source files, When I run the test, I get the following error

```
Module not found: Error: Cannot resolve module 'ComponentStyle' in the file location. Have tried searching but couldn't find any help.
```

**Comment by boui** [comment]
Used JSON.stringify on externals and it worked for me

**Comment by gholtslander-va** [comment]
You could try using a test specific webpack config that uses ProvidePlugin to provide a dummy version of it or something?

**Comment by SimulatedGREG** [comment]
Any status on this? Would really like a solution or potential work-around.

**Comment by luchillo17** [comment]
I'm having the same issue but with a different approach, i have `express-graphql` as a git SubModule, and i added it to externals config, it works great when running the app, however when doing it in karma it says `Uncaught Error: Cannot find module '../express-graphql'`.

After some digging i found the file that makes the import shows the root `/` folder for `__dirname`, i think here lies my error, any advise?

Also for the same file i show the `process.cwd()` output as `/Users/aplicaciones2/Documents/tao-graphql-api`, so idk what to do.

**Comment by qlqllu** [comment]
Any updates?

**Comment by codymikol** [comment]
Closing due to the age of this ticket, if you're still having issues with the current build feel free to open a new ticket with the relevant information and I'll help as best I can!
