### ISSUE TITLE
`SyntaxError: Use of reserved word 'import'` when using ES6 with Babel

### ISSUE THREAD

**Issue by rafaeleyng** [ryanclark/karma-webpack#129]
I'm having a really hard time trying to setup testing in my application. We are using Angular, Webpack, ES6 with Babel.

My relevant files are as follows:

**karma.conf.js**

```
require('babel-core/register');
module.exports = require('./karma.conf.babel').default;
```

**karma.conf.babel.js**

```
import webpackDevConfig from './webpackDevConfig'

export default (config) => {
  config.set({
    frameworks: [
      'jasmine'
    ],

    files: [
        'test/test_index.js'
    ],

    preprocessors: {
        'test/test_index.js': ['webpack']
    },

    browsers: [
      'PhantomJS',
    ],

    singleRun: true,

    webpack: webpackDevConfig,

    webpackMiddleware: {
      noInfo: true
    }
  });
};
```

**webpackDevConfig.js**

```
export default (config) => {
    return {
        module: {
            loaders: [
                {
                    test: /\.js?$/,
                    exclude: /(node_modules)/,
                    loader: 'ng-annotate?map=false!babel-loader?cacheDirectory=true&presets[]=es2015',
                },
        // ... other loaders
            ],
        },
        // ... other config
    }
}
```

**test/test_index.js**

```
import 'angular';
import 'angular-mocks/angular-mocks';

const testsContext = require.context('.', true, /.spec$/);
testsContext.keys().forEach(testsContext);
```

Error is:

```
10 06 2016 17:34:11.421:INFO [karma]: Karma v0.13.22 server started at http://localhost:9876/
10 06 2016 17:34:11.443:INFO [launcher]: Starting browser PhantomJS
10 06 2016 17:34:12.860:INFO [PhantomJS 2.1.1 (Mac OS X 0.0.0)]: Connected on socket /#4wX21ZNf-Gdt6B2nAAAA with id 30689295
PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
  SyntaxError: Use of reserved word 'import'
  at /Users/rafael/myproject/test/test_index.js:47


npm ERR! Test failed.  See above for more details.
```

**Comment by MrArnoldPalmer** [comment]
Having this same issue. Let me know if you find a fix.

**Comment by MrArnoldPalmer** [comment]
@rafaeleyng I just resolved me issue. My default webpack config was not an object but an array of multiple configs, 1 for client and 1 for server.

in karma.conf.js I changed

```
    webpack: webpackConfig
```
to
```

**Comment by MikaAK** [comment]
I've run into this as well and ended up changing my imports to `require` inside my `test_index`. Just now, I also tried switching back from `require` but found that `import` is now working without errors 😖. @d3viant0ne or @goldhand  have either of you run into this before?

**Comment by d3viant0ne** [comment]
I've gotten the import syntax working with babel / AVA, haven't tried it with Karma yet. That said, given we are about to do this for `karma-webpack` we'll figure it out.

**Comment by dganoff** [comment]
+1

**Comment by goldhand** [comment]
I think this works with AVA because it supports es6 syntax natively. This won't work with karma tests because node doesn't support `import` statements yet.
A work around is to use `babel-cli` to run your tests.

```json

"test": "NODE_ENV=test npm run babel -- ./node_modules/karma/bin/karma start",

```

**Comment by MikaAK** [comment]
I actually have this working with imports and karma at work,  I'll try and dig a bit deeper and figure out why it works

**Comment by rafaeleyng** [comment]
(I haven't been able to test any of the proposed solutions in my scenario yet, hope that someday I will)

**Comment by tdukart** [comment]
If it helps, I'm running into a similar issue on one project, yet another one works like a charm. And I wrote them both this weekend.

Working project: https://github.com/tdukart/hue-colors (logs at https://travis-ci.org/tdukart/hue-colors/builds/154053186)
Broken project: https://github.com/tdukart/lightogram

I'm not sure if it's because `lightogram` depends on `hue-colors` and they're both ES6.

**Comment by hypery2k** [comment]
any news on this?

**Comment by hypery2k** [comment]
i found the error for, if you look at the looks you see that you are using karma 0.13.22. Try upgrade your dependency to karma 1.2.0 and it's working

**Comment by MikaAK** [comment]
I tested out upgrading to `karma 1.2.0` and it's still happening for me in one of my projects

**Comment by MikaAK** [comment]
Ok I think I figured this out. After some testing on one of my projects I noticed import statements started to work after two requirements were met (not doing one of these results in an import error):
1) You must have a `require('babel-register')` in your `karma.conf.js`
2) You must have a loader active for the targeted entrypoint (example below)

`karma-shim.js`
```javascript
import 'something'
import 'another-thing'
```

`webpack.config.babel.js`
```javascript
export default {
   module: {
     loaders: [{
        test: /\.js$/,
        loader: 'babel',
        include: ['./karma-shim']
     }]
   }
}
```

Would anyone else be able to test this out? If this is the case I can add a note in the README

**Comment by hypery2k** [comment]
it seems to be that this is path issue. You have to set your basePath correctly to '.'. This worked out for me. You don't need babel-register

**Comment by MikaAK** [comment]
@hypery2k i do have `basePath` set like that. What language are you using? With typescript it doesn't seem to work without `babel-register`. I get ```
ERROR [config]: Invalid config file!
  SyntaxError: Unexpected token import
```
with `babel-register` and  no loader I get 
```
PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
  SyntaxError: Use of reserved word 'import'
```

**Comment by hypery2k** [comment]
didn't try it with typescript, just with ES6 
But I saw errors with the import, if use absolute paths instead of relative to the package root

**Comment by MikaAK** [comment]
Can you define `package root`? Not quite sure what that is :3

**Comment by strike-sbolel** [comment]
I'm having the same issue with TypeScript, but only on Travis-CI. Locally, everything works fine.

#### Error in Travis-CI:

```
START:
ts-loader: Using typescript@2.0.0 and /.../tsconfig.json
16 09 2016 23:31:22.741:INFO [karma]: Karma v1.3.0 server started at http://localhost:9876/
16 09 2016 23:31:22.743:INFO [launcher]: Launching browser PhantomJS with unlimited concurrency
16 09 2016 23:31:22.750:INFO [launcher]: Starting browser PhantomJS
16 09 2016 23:31:24.080:INFO [PhantomJS 2.1.1 (Linux 0.0.0)]: Connected on socket /#ahv1Z7tbN807BGERAAAA with id 69888324
PhantomJS 2.1.1 (Linux 0.0.0) ERROR
  SyntaxError: Use of reserved word 'export'
  at webpack:///~/angularfire2/index.js:1:0 <- karma.entry.js:50462
```

#### Files

- karma/webpack config
  - [karma.conf.js](https://gist.github.com/strike-sbolel/302fe298296d9abb90ba3ca3721ef286)
  - [karma.entry.js](https://gist.github.com/strike-sbolel/b962929a3df0a0fd3bbfff5b9266a62c)
  - [webpack.config.js](https://gist.github.com/strike-sbolel/43f13a27c6aaa44b2768d0a81797dda8)
- sources
  - [vendor.ts](https://gist.github.com/strike-sbolel/5bef8e38dec089ce35b944100326da61)
  - [polyfills.ts](https://gist.github.com/strike-sbolel/e5d9368a13d66590a71c1d23565b6729)
- travis.yml and dependencies
  - [.travis.yml](https://gist.github.com/strike-sbolel/3c0fd3f095d1a734fa4f8c83db9a4d3c)
  - [package.json](https://gist.github.com/strike-sbolel/a2a1fd21e9cd48a46341db268b5c35f8)

I'd appreciate any help.

**Comment by MikaAK** [comment]
@strike-sbolel try one of my suggested fixes above and let me know if it works for you

**Comment by evanjmg** [comment]
+1

**Comment by pkawiak** [comment]
Maybe this will be of use for someone: we have encountered this issue when running our karma tests on specific dev box. It was executing fine on all other boxes. After some investigation we've found out that build was failing when it was execuded in **windows symlink**ed directory.

**Comment by nalwayaabhishek** [comment]
Any update on this issue on mac it is working fine but same code is giving error on ubuntu 

`SyntaxError: Use of reserved word 'import'
  at webpack:///~/chai-enzyme/~/react-element-to-jsx-string/index.js:1:0 <- tests/test-bundler.js:24270`

**Comment by lizhong8532** [comment]
Same problem too, How fix on Mac OS?

When running test task and notice the error:
```
PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
  SyntaxError: Use of reserved word 'import'
  at webpack:///test/unit/util/foo.spec.js:1:0 <- /Users/lee/WebstormProjects/uGraph/test/unit/index.js:85
```

I added babel loader to project of karma.config.js:
```
		loaders: [
			{
				test: /\.js$/,
				loader: 'babel',
				exclude: /node_modules/
			}
		]
```

 I has been working on this problem two days . But the problem still can't fix.

**Comment by wembernard** [comment]
Same problem here. Tried most of what's been written here. 

Is it ES6 related? Since Typescript has problems too, I guess it's transpilation-related. 

It's possible it's linked to https://github.com/babel/karma-babel-preprocessor

**Comment by ImranAhmed** [comment]
I started seeing this happening when I moved some folders around in my project. Updating the path in karma.conf.js fixed it.

```
preprocessors: {
      "../src/**/*.spec.ts*": ["webpack"]
    },
```

**Comment by kevinkleine** [comment]
+1 

Vuejs, Webpack, Karma -> No preprocessing of both .js and .vue files.

**Comment by juicyarts** [comment]
I ran into this issue today building a react starter kit for myself. I tried to configure it just like another application i got this working with.
* https://github.com/juicyarts/vuejs-starter 
** this is just an excerpt of something i built for a coding challange and needs some improvements..

I've built the foundation using the [vue-loader](https://github.com/vuejs/vue-loader) which installs 
* "webpack": "^2.1.0-beta.25",

A usual Webpack installation installs version 1.14. Changing the Version to the mentioned 2.1.0-beta.25 fixed the issues i had with import statements, still it doesn't seem to be a good solution :/

**Comment by matrunchyk** [comment]
Same here. I can't make it working.

**karma.conf.js**
```
const webpackConfig = require('./node_modules/laravel-mix/setup/webpack.config.js');

delete webpackConfig.entry;

module.exports = config => config.set({
    browsers: ['PhantomJS'],
    frameworks: ['jasmine'],
    // this is the entry file for all our tests.
    files: ['resources/assets/js/tests/index.js'],
    // we will pass the entry file to webpack for bundling.
    preprocessors: {
        '../resources/assets/js/**/*.js': ['webpack'],
        '../resources/assets/js/**/*.vue': ['webpack'],
    },
    // use the webpack config
    webpack: webpackConfig,
    // avoid walls of useless text
    webpackMiddleware: {
        noInfo: true,
    },
    singleRun: true,
});
```

**tests/index.js**
```
// test/index.js
// require all test files using special Webpack feature
// https://webpack.github.io/docs/context.html#require-context
const testsContext = require.context('.', true, /\.spec$/);
testsContext.keys().forEach(testsContext);
```

**test/LoginForm.spec.js**
```
// tests/LoginForm.spec.js
import Vue from 'vue';
import * as LoginForm from '../front/vue-components/LoginForm.vue';

describe('LoginForm.vue', () => {
    // asserting JavaScript options
    it('should have correct message', () => {
        expect(LoginForm.data().msg).toBe('Hello from Component A!');
    });

    // asserting rendered result by actually rendering the component
    it('should render correct message', () => {
        const vm = new Vue({
            template: '<div><test></test></div>',
            components: {
                test: LoginForm,
            },
        }).$mount();
        expect(vm.$el.querySelector('h2.red').textContent).toBe('Hello from Component A!');
    });
});
```

**Result:**
`node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/.bin/karma start karma.conf.js`

> DONE  Compiled successfully in 66ms                                                                                                     
> 
> 27 02 2017 18:57:24.054:INFO [karma]: Karma v1.5.0 server started at http://0.0.0.0:9876/
> 27 02 2017 18:57:24.056:INFO [launcher]: Launching browser PhantomJS with unlimited concurrency
> 27 02 2017 18:57:24.064:INFO [launcher]: Starting browser PhantomJS
> 27 02 2017 18:57:25.395:INFO [PhantomJS 2.1.1 (Mac OS X 0.0.0)]: Connected on socket 4AVsWe8dqE1lIneLAAAA with id 54540662
> PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
>   ReferenceError: Can't find variable: require
>   at resources/assets/js/tests/index.js:4

Require is a part of webpack [require-context](https://webpack.github.io/docs/context.html#require-context). Not sure why it can't find this symbol.

**Comment by Maximaximum** [comment]
I'm experiencing this issue as well. Weird to see it hasn't been fixed for almost 2 years

**Comment by codymikol** [comment]
I have integration tests with this scenario working on the latest version `5.0.0-alpha.6` If anyone is by chance still having this issue, please feel free to open another ticket with the relevant information!
