### ISSUE TITLE
webpack+babel = source map not works

### ISSUE THREAD

**Issue by alexey2baranov** [ryanclark/karma-webpack#176]
Hello! I am very new with Karma, sorry if i miss something.

i have a very simple test file Karma.test.js next five lines:

``` javascript
describe('Karma', function () {
    it('should done', async function () {
        throw new Error("bla");
    });
});
```

when Karma start it outputs:

> Chrome 53.0.2785 (Linux 0.0.0) Karma should done FAILED
>         Error: bla
>             at Context.<anonymous> (webpack:///test/Karma.test.js:122:0 <- test/Karma.test.js:168:28)
>             at boundThen (webpack:///test/Karma.test.js:112:0 <- test/Karma.test.js:158:26)
>             at Context.<anonymous> (webpack:///test/Karma.test.js:121:0 <- test/Karma.test.js:167:17)
> Chrome 53.0.2785 (Linux 0.0.0): Executed 1 of 1 (1 FAILED) ERROR (0.018 secs / 0.003 secs)

As you can see stack trace points to line 122. but test file has 5 lines only. What is my mistake? 

Hire is my configs
**karma.conf.js**

``` javascript
webpackConfig= require("./webpack.config");


module.exports = function (config) {
    config.set({

        // base path that will be used to resolve all patterns (eg. files, exclude)
        basePath: '',


        // frameworks to use
        // available frameworks: https://npmjs.org/browse/keyword/karma-adapter
        frameworks: ['mocha'],


        // list of files / patterns to load in the browser
        files: [
            {pattern: 'test/**/Karma.test.js', watched: false},
            // {pattern: 'test/*.test.js', watched: false},
            // {pattern: 'test/**/*.test.js', watched: false},
            /*
             {pattern: 'test/!**!/!*.test.browser.js', watched: false},
             */
        ],


        // list of files to exclude
        exclude: [],


        // preprocess matching files before serving them to the browser
        // available preprocessors: https://npmjs.org/browse/keyword/karma-preprocessor
        preprocessors: {
            'test/**/*.test.js': ["webpack", 'sourcemap'],
            'test/**/*.test.browser.js': ["webpack", 'sourcemap'],
        },

        // karma watches the test entry points
        // (you don't need to specify the entry option)
        // webpack watches dependencies

        // webpack configuration
        webpack: webpackConfig,


        webpackMiddleware: {
            // webpack-dev-middleware configuration
            noInfo: true,
            stats: 'errors-only',
        },

        // test results reporter to use
        // possible values: 'dots', 'progress'
        // available reporters: https://npmjs.org/browse/keyword/karma-reporter
        reporters: ['progress'],


        // web server port
        port: 9876,


        // enable / disable colors in the output (reporters and logs)
        colors: true,


        // level of logging
        // possible values: config.LOG_DISABLE || config.LOG_ERROR || config.LOG_WARN || config.LOG_INFO || config.LOG_DEBUG
        logLevel: config.LOG_INFO,


        // enable / disable watching file and executing tests whenever any file changes
        autoWatch: true,


        // start these browsers
        // available browser launchers: https://npmjs.org/browse/keyword/karma-launcher
        browsers: ['Chrome'],


        // Continuous Integration mode
        // if true, Karma captures browsers, runs the tests and exits
        singleRun: false,

        // Concurrency level
        // how many browser should be started simultaneous
        concurrency: Infinity
    })
}

```

**webpack.config.js**

``` javascript
var webpack= require('webpack');
module.exports = {
    entry: {
    },
    output: {
        path: __dirname+'/bin',
        filename: '[name].webpack.js',
        publicPath: 'http://localhost:8081/bin'
    },
    devtool: 'inline-source-map',
    plugins:[
        new webpack.NoErrorsPlugin(),
        new webpack.dependencies.LabeledModulesPlugin(),
        new webpack.IgnorePlugin(/vertx/),
    ],
    watch: true,
    module: {
        loaders: [
            { test: /\.json$/, loader: 'json', },
            { test: /\.md$/, loader: "html!markdown" },
            { test: /\.js$/, loader: 'babel' }
        ]
    }
};
```

**.babelrc**

``` javascript
{
    "sourceMaps": "inline",
    "plugins": [
        "fast-async",
        "transform-class-properties",
        "transform-es2015-parameters",
        "transform-es2015-destructuring"
    ],
    "ignore": [
        "./node_modules/**/*.js"
    ]
}
```

**Comment by MikaAK** [comment]
I've encountered this with TS before, we should investigate into this more

**Comment by abirmingham** [comment]
+1

**Comment by paulsouche** [comment]
Hi,

I have the same issue with inline source maps using typescript and babel. Generated content [here](https://github.com/webpack/karma-webpack/blob/v1/src/karma-webpack.js#L228) has no inline source maps.

I've made some test on it and it seems that ts-loader do not handle sourcemap correctly. My repo [here](https://github.com/paulsouche/karma-webpack-176).

Will investigate on ts-loader.

Thx

**Comment by sherzinger** [comment]
I have exactly the same issue and hope this is the right place to address it.

In fact it is even worse if you use imports in your test file and then set a breakpoint somewhere in the test code.
For instance `import foo from 'fooProvider'` with foo being a constant 3, will be shown as something like __WEBPACK_IMPORTED_MODULE_2_fooProvider__.a

**Comment by TimYi** [comment]
I have the same issue. The sourcemap is not correct.

**Comment by abirmingham** [comment]
I don't know if you're using babel or not, but I am. I was able to track down [this](https://github.com/babel/babel/issues/2597) issue, which explains why babel emits symbols which cannot be sourcemapped. It seems that this is a shortcoming of the sourcemap spec and/or chromium. I would guess that TypeScript is subject to the same shortcoming when emitting ES5.

**Comment by pierluca** [comment]
Same issue as well.

**Comment by dylan-chong** [comment]
Same issue as well with js. Has any work being done on this issue?

**Comment by ocoka** [comment]
Ok people, I tried to manage this for two days, and found solution,
it was mentioned in
#109
and **https://github.com/aaronjensen/karma-webpack**
you need to use "alternative way to run your tests", through on JS file that use *require.context* to load all tests

**Comment by codymikol** [comment]
I'm aggregating all tickets about source-map issues here ==> #485 .
