### ISSUE TITLE
Receiving warnings and errors and not sure where to start debugging...

### ISSUE THREAD

**Issue by joetidee** [ryanclark/karma-webpack#216]
I have set-up karma-webpack and when I run `karma start` with only the following test in place...:

const assert = require('assert');
var bcrypt = require('bcrypt');

describe('encryptPass', function() {
    it('returned hash should return ', function() {
        assert.equal(1,1);
    });
});

I get the following warnings (and about 50 more beyond this)...:

```
WARNING in ./~/bcrypt/bcrypt.js
Critical dependencies:
6:15-36 the request of a dependency is an expression
 @ ./~/bcrypt/bcrypt.js 6:15-36

WARNING in ./~/bcrypt/~/node-pre-gyp/lib/pre-binding.js
Critical dependencies:
19:22-48 the request of a dependency is an expression
 @ ./~/bcrypt/~/node-pre-gyp/lib/pre-binding.js 19:22-48

WARNING in ./~/bcrypt/~/node-pre-gyp/lib/util/versioning.js
Critical dependencies:
15:20-67 the request of a dependency is an expression
 @ ./~/bcrypt/~/node-pre-gyp/lib/util/versioning.js 15:20-67

WARNING in ./~/bcrypt/CHANGELOG.md
Module parse failed: /tidee/auth_app/node_modules/bcrypt/CHANGELOG.md Unexpected character '#' (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected character '#' (1:0)
    at Parser.pp$4.raise (/tidee/auth_app/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp$7.getTokenFromCode (/tidee/auth_app/node_modules/acorn/dist/acorn.js:2756:10)
    at Parser.pp$7.readToken (/tidee/auth_app/node_modules/acorn/dist/acorn.js:2477:17)
    at Parser.pp$7.nextToken (/tidee/auth_app/node_modules/acorn/dist/acorn.js:2468:15)
    at Parser.parse (/tidee/auth_app/node_modules/acorn/dist/acorn.js:515:10)
    at Object.parse (/tidee/auth_app/node_modules/acorn/dist/acorn.js:3098:39)
    at Parser.parse (/tidee/auth_app/node_modules/webpack/lib/Parser.js:902:15)
    at NormalModule.<anonymous> (/tidee/auth_app/node_modules/webpack/lib/NormalModule.js:104:16)
    at NormalModule.onModuleBuild (/tidee/auth_app/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/tidee/auth_app/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
    at /tidee/auth_app/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/tidee/auth_app/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /tidee/auth_app/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:415:3)
 @ ./~/bcrypt ^\.\/.*$
```

Would appreciate a heads-up on what is happening here and some posisble solutions. Seems like it might be a configuration issue involving either resolving/including node_modules (?)

**Comment by d3viant0ne** [comment]
This by any change public. From the logging, it feels more like config issue but i'd need to see it.

Obviously loading the changelog.md is less than optimal so something needs tweaking.

**Comment by joetidee** [comment]
It's not, but can set up access to the Bitbucket repo if you send me your email address. Else, could post webpack/karma config files if this would help (?)

**Comment by d3viant0ne** [comment]
@joetidee - My email is public in my profile on github and getting access to the project briefly will be the fastest way to get this resolved.

**Comment by joetidee** [comment]
Much appreciated - have sent details to your address.

**Comment by d3viant0ne** [comment]
Give me a minute to pull a few espresso shots and I will take a look

**Comment by d3viant0ne** [comment]
@joetidee - So while I am in here anyway, want to just get the upgrade to `webpack 2.2.0` out of the way?

**Comment by joetidee** [comment]
Is this necessary?

**Comment by d3viant0ne** [comment]
Besides a less complex config & the fact 1.x will be deprecated at some point...

Performance, performance, performance.  Lots of bug fixes and usability improvements.

- DllReferencePlugin ( Stupid fast dev rebuilds. Seriously stupid 50 - 80% )
- Bundle performance budgets (i.e. `vendor.[hash].js` > 250kb === console warning)
- loader-runner: loaders can return a Promise.
- ChunkModuleIdRangePlugin: added experimental plugin to assign module ids to a chunk. (related to Long Term Caching)
- UglifyJs: version updated. ( Better tree shaking )
- MultiCompiler: dependencies parameter added. Allows to specify dependencies with multiple configurations. They are compiled in this order.

Though the really important reason being webpack 2.2.0 was ready long before the actual official release. Most if not all the major plugins / loaders are already focused on `v2.2.0` which means it will become more and more difficult to get updates for 1.14.0 ( not official in any way, my opinion )

Brass tacks, in reality you will have to upgrade sooner or later. This just happens to be a major release that I wanted to upgrade to.

**Comment by joetidee** [comment]
Sounds very positive. Hope that the tools I use will be 2.2 ready.

**Comment by d3viant0ne** [comment]
Actually `webpack-node-externals` may not be ready for 2.2 all the other libs in your `package.json` will work just fine in 2.x. I use 90% of them personally.

**Comment by joetidee** [comment]
There doesn't seem to be any obvious reference to actually using this package directly in this project ...(?)

**Comment by joetidee** [comment]
Has there been any progress on the errors that are being thrown ?

**Comment by codymikol** [comment]
Closing due to the age of this ticket, if you're still having issues with the current build feel free to open a new ticket with the relevant information and I'll help as best I can!
