### ISSUE TITLE
[Bug] Core-js not working when in spec file

### ISSUE THREAD

**Issue by luchillo17** [ryanclark/karma-webpack#219]
**I'm submitting a bug report**

**Webpack version:**
2.2.0

**Webpack Karma version**:
2.0.2

**Karma version**:
1.4.1

**Please tell us about your environment:**
OSX 10.x Sierra

**Browser:** NW.js

**Current behavior:**
`core-js` imports inside imported file in spec doesn't work properly, getting error like:
```ts
Uncaught TypeError: undefined is not a function
```

The error happens the moment i add this line to the file i'm supposed to test:
```ts
// server.ts
import 'core-js';
...
console.log(Object.entries(Express)); // Agresor line here with the `Object.entries`.
...
```

**Expected/desired behavior:**
I was expecting to be able to load a polyfill like `core-js` and just use its functions, when using the webpack dev config and executing the Node server, it works flawlessly, but when it's run from the spec file it breaks.

**How to repro:**
1. Clone repo https://github.com/Luchillo/Node-typescript-karma-base
2. Switch to branch `feature/core-js_support`
3. Run `npm i && npm t``

It should execute the tests and show something like this:
![image](https://cloud.githubusercontent.com/assets/9698639/22556171/3cf8bb90-e934-11e6-89a7-99e5ce6a0029.png)

**Comment by codymikol** [comment]
Going to close this as it's very old at this point, if you happen to still be having issues with the latest build, I can help you if you open a new ticket with relevant information.
