### ISSUE TITLE
karma runs rebuild too many times after updating entry file

### ISSUE THREAD

**Issue by pavel06081991** [ryanclark/karma-webpack#223]
Here is my karma config:
```
module.exports = function (config) {
  config.set({
    browsers: ['Chrome'],
    singleRun: true,
    frameworks: [
      'mocha',
      'chai',
      'sinon'
    ],
    files: [
      'tests/unit/tests.js'
    ],
    plugins: [
      'karma-chrome-launcher',
      'karma-mocha',
      'karma-chai',
      'karma-sinon',
      'karma-sourcemap-loader',
      'karma-webpack',
      'karma-coverage'
    ],
    preprocessors: {
      'tests/unit/tests.js': [
        'webpack',
        'sourcemap'
      ]
    },
    reporters: [
      'progress',
      'coverage'
    ],
    webpack: {},
    coverageReporter: {
      type: 'html',
      dir: 'coverage/'
    }
  });
};
```
When I update 'tests/unit/tests.js', for example I add indent and then save this file, and after this I run "karma start" and after this in console output I see that webpack build runs about 19 times. Then I run "karma start" again and all works okay, webpack build runs only 1 time. Maybe you know why this happens?

**Comment by DavidKk** [comment]
+1 

![image](https://cloud.githubusercontent.com/assets/4200041/24187362/99f0896e-0f17-11e7-823e-59d93ce832f8.png)

my karma config
![image](https://cloud.githubusercontent.com/assets/4200041/24187409/c18f9b68-0f17-11e7-875d-7b17037f0cec.png)

just run webpack
![image](https://cloud.githubusercontent.com/assets/4200041/24187483/13c45b94-0f18-11e7-8558-6bc0c2365410.png)

**Comment by DavidKk** [comment]
node@v7.6.0
karma@1.5.0
webpack@2.3.0

**Comment by DavidKk** [comment]
it always build 4 times

![image](https://cloud.githubusercontent.com/assets/4200041/24195998/e77f3cce-0f36-11e7-9856-d23c8e832b48.png)

just run webpack
![image](https://cloud.githubusercontent.com/assets/4200041/24196213/e29db59a-0f37-11e7-8e54-01761d058dcf.png)

my karma config
![image](https://cloud.githubusercontent.com/assets/4200041/24196239/fa1451b6-0f37-11e7-9cf4-1bdf99f2efb3.png)

osx@10.12.3
node@v7.6.0

├── karma@1.5.0
├─┬ karma-webpack@2.0.3
│ └── webpack-dev-middleware@1.10.1
└── webpack@2.3.0

**Comment by pavel06081991** [comment]
Is there any updates on this issue?

**Comment by onlywei** [comment]
I'm experiencing this issue as well:

karma@1.7.1
karma-webpack@2.0.6
webpack@3.8.1

**Comment by drawyan** [comment]
We are seeing the same issue, it bundles multiple times even a small change is made, then when you re-run, it becomes normal.

**Comment by codymikol** [comment]
Closing as this does not seem to be an issue in the 5.0.0 release, if anyone is still having problems, please free to open an issue and I'll be happy to assist!
