### ISSUE TITLE
External source maps don't work

### ISSUE THREAD

**Issue by asapach** [ryanclark/karma-webpack#224]
**I'm submitting a bug report / feature request**

**Webpack version:**
2.x

**Webpack Karma version**:
2.x

**Karma version**:
1.x

**Please tell us about your environment:**
Windows 10

**Browser:** Any

**Current behavior:**
It looks like the only supported way to make source maps work (other than `eval` maps) is to use `devtool: 'inline-source-map'` in conjunction with [`karma-sourcemap-loader` preprocessor](https://github.com/webpack-contrib/karma-webpack#source-maps).

When you try to use `devtool: 'source-map'` to produce external source maps:
* Karma ignores them, because the preprocessor [checks the filesystem](https://github.com/demerzel3/karma-sourcemap-loader/blob/53d758fbfdf7e94e693cc96548516a073d0a8b67/index.js#L42) for the non-existent file.
* Browsers ignore them, because karma returns 404, e.g. `http://localhost:9876/base/test.js.map` does not exist, while `http://localhost:9876/_karma_webpack_/test.js.map` does.

**Expected/desired behavior:**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.**
The karma/webpack config is [typical](https://github.com/webpack-contrib/karma-webpack#alternative-usage), except:
```js
webpack: {
  // ...
  devtool: 'source-map'
}
```

* **What is the expected behavior?**
Maybe there's a way to bypass `karma-sourcemap-loader` and set [`file.sourceMap`](https://github.com/demerzel3/karma-sourcemap-loader/blob/53d758fbfdf7e94e693cc96548516a073d0a8b67/index.js#L12) in `karma-webpack` directly? That way source maps will be picked up by karma.
Another piece of the puzzle would be configuring `SourceMapDevToolPlugin` to point to `_karma_webpack_` middleware to allow browsers to download the source map.

* **What is the motivation / use case for changing the behavior?**
The problem is that while inline source maps are perhaps the simplest and reliable, they are not the most efficient. Enabling external source maps allows for more flexible configurations and should boost performance.

**Comment by mnzaki** [comment]
There's an attempt here https://github.com/aaronjensen/karma-webpack#file-faster but it doesn't seem to work (for me at least). Browser tries to load the sourcemap from a wrong location.

**Comment by likebeats** [comment]
Any updates on this?

**Comment by sergei-startsev** [comment]
External sourcemaps can be setup by using [writeToDisk](https://github.com/webpack/webpack-dev-middleware#writetodisk) option passed to `webpack-dev-middleware`, however there's an issue with supporting this option in `karma-webpack`, see #405.

Here's an attempt to setup external sourcemaps (dist folder is hardcoded in `middleware.js` because of  #405 issue): https://github.com/sergei-startsev/karma-stacktrace/tree/master/examples/qunit

**Comment by codymikol** [comment]
I'm aggregating all tickets about source-map issues here ==> https://github.com/ryanclark/karma-webpack/issues/485 .
