### ISSUE TITLE
Add alternative usage to README

### ISSUE THREAD

**Issue by CTaylor1118** [ryanclark/karma-webpack#242]
## **BEFORE YOU SUBMIT** please read the following:

**I'm submitting a feature request**

**Webpack version:**
2.3.3

**Webpack Karma version**:
2.0.3

**Karma version**:
1.6

**Please tell us about your environment:**
OSX 10.12

**Browser:** [Phantom XX | Chrome XX | Firefox XX | IE XX | Safari XX | Other XX]

**Expected/desired behavior:**
Update README with another alternative usages for requiring files that allows for filtering files at compile time.
```javascript
// test/test_index.js

// require all modules ending in "_test" from the
// current directory and all subdirectories
var testsContext = require.context(".", true, karma.TESTFILTER);
testsContext.keys().forEach(testsContext);
```

```javascript
// Karma configuration
module.exports = function(config) {
  config.set({
    // ... normal karma configuration
    files: [
      // all files ending in "_test"
      {pattern: 'test/*_test.js', watched: false},
      {pattern: 'test/**/*_test.js', watched: false}
      // each file acts as entry point for the webpack configuration
    ],

    preprocessors: {
      // add webpack as preprocessor
      'test/*_test.js': ['webpack'],
      'test/**/*_test.js': ['webpack']
    },

    webpack: {
      // karma watches the test entry points
      // (you don't need to specify the entry option)
      // webpack watches dependencies

      // webpack configuration
      ...
      plugins: [new webpack.DefinePlugin({
        'karma.TESTFILTER': /_test$/
      })
    },

    webpackMiddleware: {
      // webpack-dev-middleware configuration
      // i. e.
      stats: 'errors-only'
    }
  });
};
```

* **What is the motivation / use case for changing the behavior?**
This configuration allows for passing in a filtering RegExp from the command line. This may be useful for those who want to be able to compile a subset of tests without using grep to run the desired tests.

**Comment by codymikol** [comment]
Closing as this is a few years old, I think this is one of many ways to set up configuration, not sure if it necessarily needs to be in the documentation.
