### ISSUE TITLE
Support custom `customPreprocessors` options

### ISSUE THREAD

**Issue by KurtWagner** [ryanclark/karma-webpack#254]
**I'm submitting a feature request**

It would be great to support `customPreprocessors` as described in the karma docs [here](http://karma-runner.github.io/1.0/config/preprocessors.html). This would allow for different preprocessing configurations. For example, you may want to preprocess test/spec files differently from application modules.

Your karma config would be something like

```
customPreprocessors: {
  webpackWithX: {
    base: "webpack",
    options: {
      webpack: {...},
      webpackMiddleware: {...}
    }
  },
  webpackWithY: {
    base: "webpack",
    options: {
      webpack: {...}
    }
  }
}
```
 
From looking at the source it seems like the construction of `Plugin` would need to be done in `createPreprocessor` function with the injected values plus the addition of `args`. Then something like

```javascript
var options = args.options;
var webpackPlugin = new Plugin(
    options.webpack || webpackOptions,
    // etc
);
return function factory(...) {...};
```
(or maybe only `options` or the other, I haven't looked too deep into it)

With some guidance I'm happy to contribute a PR if this is something you want to support.

**Comment by codymikol** [comment]
Hey Kurt, is this something you are still interested in?
