### ISSUE TITLE
Requiring files for coverage not working properly

### ISSUE THREAD

**Issue by TheDutchCoder** [ryanclark/karma-webpack#256]
**I'm submitting a bug report**
The documentation says we can use a structure like this to include/exclude files from coverage:
``` js
const srcContext = require.context('../../src/framework', true, /\.vue$/)
srcContext.keys().forEach(srcContext)

```

However, the RegEx doesn't do anything and webpack simply includes every single file it runs into, not taking the RegEx into account at all.

**Webpack version:**
2.2.1

**Webpack Karma version**:
2.0.2

**Karma version**:
1.4.1

**Please tell us about your environment:**
OSX 10.12.5 (16F73)

**Browser:**
PhantomJS prebuilt 2.1.14

**Current behavior:**
`srcContext` in the entry file doesn't actually do anything.

The following statement doesn't only take `.vue` file, it just includes everything webpack runs into:
`const srcContext = require.context('../../src/framework', true, /\.vue$/)`

In fact, even my index.js file in the test directory is included.

**Expected/desired behavior:**
Only `.vue` files to be included for coverage or anything I match with the RegEx.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.**
I'm using `vue-cli webpack` to setup a project. Everything is pre-configured. Just starting a new project, adding files to the project and adjusting `index.js` shows this bug.

* **What is the expected behavior?**
See above

* **What is the motivation / use case for changing the behavior?**
This feature is documented but apparently not working (in this case), which throws off our coverage reports by a lot.

**Comment by Argeento** [comment]
Try to configure [babel-plugin-istanbul](https://github.com/istanbuljs/babel-plugin-istanbul) instead

`.babelrc`

```javascript
...
  "env": {
    "test": {
      "presets": ["env", "stage-2"],
      "plugins": [
        ["istanbul", {
          "include": ["**/*.vue"],
          "exclude": ["**/*.spec.js"]
        }]
      ]
    }
  }
...
```

**Comment by codymikol** [comment]
Closing as this is 3 major versions behind and I'm unable to triage. If you're still having issues on the current stable release 5.0.0, feel free to open another issue and I'll be happy to assist!
