### ISSUE TITLE
Async load webpack config

### ISSUE THREAD

**Issue by kontrollanten** [ryanclark/karma-webpack#272]
**I'm submitting a feature request**

**Current behavior:**
karma-webpack will fail to parse the webpack property in the configuration when a the webpack config is is async loaded.

```
const webpackConfig = {
  entry: ...
}

module.exports = config => {
  config.set({
    webpack: new Promise(resolve => resolve(webpackConfig)),
  });
}
```

**Expected/desired behavior:**
Accept async configurations.

* **What is the motivation / use case for changing the behavior?**
As Webpack 2+ has implemented this behavior https://github.com/webpack/webpack/issues/2697, there's some modules that depends on it. I'm using [electron-webpack](http://webpack.electron.build), which only works with async configurations, and would like to use karma-webpack for my tests.

**Comment by langri-sha** [comment]
Using [`deasync`](https://www.npmjs.com/package/deasync) in a pinch helps.
