### ISSUE TITLE
AngularJS bundle not being loaded by karma

### ISSUE THREAD

**Issue by tihomir-kit** [ryanclark/karma-webpack#274]
Hi, I already [asked on SO](https://stackoverflow.com/questions/47045159/karma-webpack-not-loading-angularjs-bundle), but the question got very low visibility and I don't believe I'll get an answer there. So I hope you won't mind too much that I'm asking here. I also asked on gitter, but got no responses. 

If you could just please hear me out, I suspect my issue is probably something trivial which I'm unable to see and you might easily spot it. I already tried everything I could think of and am practically out of ideas at this point.

**Webpack version:**
v3.3.0

**Webpack Karma version**:
v2.0.5

**Karma version**:
v1.7.1

**Please tell us about your environment:**
Windows 10

**Browser:** [PhantomJS] (karma-phantom-launcher v1.0.4)

**Issue:**

I described everything in great detail in that SO thread but this is the short version:

Basically my issue is that I believe the AngularJS bundle is not being loaded by karma. I use AngularJS written in Typescript and the webpack transpiles it into JS and for all the dev purposes - it works great. It builds the app, runs it, and it works fine in the browser. 

However, when I try to wire it up with karma-webpack, karma runs, jasmine runs, but the app does not get loaded - I don't see any console.logs that are supposed to come from the app (this worked with my old gulp setup) and I can't even inject a simple service with angular-mocks so I could do a simple test of a service method.

For how I understand it, my setup should work but it doesn't and I have no idea why.

If this it's too much hassle for you guys - I can totally understand you. In that case just ignore this and close the case. But, I figured if anyone will know how to help - it will be you guys.

In any case - thanks a lot! Cheers.

**Comment by pootzko** [comment]
I extracted a few files into a simple app and put it to a [fresh repo](https://github.com/pootzko/karma-webpack-angularjs) so the issue could be easily reproduced.

```sh
npm install
npm run serve:dev # run the app
npm run test # run karma tests
```

**Comment by jesujcastillom** [comment]
Create file at the root of your directory with the following content

```javascript
const testsContext = require.context(".", true, /_test$/)

testsContext.keys().forEach(testsContext)
```

Make this the only file in your files and preprocessors object array (in my case the file is called webpack.tests.js)

```javascript
files: ['webpack.tests.js'],
preprocessors: {
      'webpack.tests.js': ['webpack', 'sourcemap'],
    },
```

At the beginning of your `webpack.tests.js` file (or the name you put it), add the lines that import angular, angular-mocks, polyfills and such, it should work

**Comment by MEChasle** [comment]
Hi @jesujcastillom, 
I have same issue. I think karma not load bundle created by `preprocessors` `webpack`.
In your last example, you are importing again your raw sources and do not use bundle created by `webpack`.
Do I correctly understand ?
If I do, how could we use webpack bundle ?
Thanks for your answer

**Comment by codymikol** [comment]
Closing as this is quite an old ticket and @jesujcastillom seems to have a solution posted. If you are still having problems with the current build, feel free to open another issue and I'll assist as best I can!
