### ISSUE TITLE
Recently modified files get rebundled repeatedly for a few seconds.

### ISSUE THREAD

**Issue by AlexanderOMara** [ryanclark/karma-webpack#280]
**I'm submitting a bug report**

**Webpack version:**
3.9.1

**Webpack Karma version**:
2.0.6

**Karma version**:
1.7.1

**Please tell us about your environment:**
OSX 10.12

**Browser:**
Irrelevant

**Current behavior:**
When run on a recently modified file, this plugin rebundles the same file over and over again for a few seconds for no apparent reason.

**Expected/desired behavior:**
Expected the plugin to only bundle the file once.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.**
Using [this example repo](https://gist.github.com/AlexanderOMara/25828f210f11c4d0463c3bdb8ebc3b97), after `npm install` (or `yarn install`), run the following command:

    touch test.spec.js && node_modules/.bin/karma start --no-browsers

You will see that webpack keeps rebundling the file over and over again for a  few seconds, producing [a lot of output](https://gist.githubusercontent.com/AlexanderOMara/25828f210f11c4d0463c3bdb8ebc3b97/raw/372928f049ab9e5d12693d8d41228ec12dd5df26/example_output.txt).

However if you wait a few seconds (~8 seems to be the tipping point), it behaves as expected:

    touch test.spec.js && sleep 10 && node_modules/.bin/karma start --no-browsers

* **What is the expected behavior?**

Recently modified files should bundle once, same as older files.

* **What is the motivation / use case for changing the behavior?**

This behavior doesn't seem to make any sense, and results in a lot of unnecessary work and output.

----

Possible hint: I did a little poking around attempting to debug the issue, and it looks like [this callback](https://github.com/webpack-contrib/karma-webpack/blob/0d075b019c99f06e7257a49d3da847a0b34f8d34/src/karma-webpack.js#L87-L93) may be triggering the recompiled on the `invalid` event. Beyond that, I really don't know what is going on here.

**Comment by codymikol** [comment]
Closing as this does not seem to be an issue on the current major release 5.0.0, if you are still having trouble with the current build feel free to open another issue and I'll be happy to assist!
