### ISSUE TITLE
Obscure __zone_symbol__currentTask error during previously working karma tests in Angular app on PhantomJS

### ISSUE THREAD

**Issue by wcainboundary** [ryanclark/karma-webpack#290]
**I'm submitting a bug report**

**Webpack version:**
2.2.1

**Webpack Karma version**:
2.0.9
karma-webpack@2.0.9

**Karma version**:
1.7.0

**Please tell us about your environment:**
Ubuntu 16

**Browser:** PhantomJS 2.1.1

**Current behavior:**
```
[INFO] PhantomJS 2.1.1 (Linux 0.0.0) ERROR
[INFO]   {
[INFO]     "__zone_symbol__currentTask": {
[INFO]       "type": "microTask",
[INFO]       "state": "notScheduled",
[INFO]       "source": "Promise.then",
[INFO]       "zone": "<root>",
[INFO]       "cancelFn": null,
[INFO]       "runCount": 0
[INFO]     }
[INFO]   }
[INFO] 
[INFO] PhantomJS 2.1.1 (Linux 0.0.0) ERROR
[INFO]   {
[INFO]     "__zone_symbol__currentTask": {
[INFO]       "type": "microTask",
[INFO]       "state": "notScheduled",
[INFO]       "source": "Promise.then",
[INFO]       "zone": "<root>",
[INFO]       "cancelFn": null,
[INFO]       "runCount": 0
[INFO]     }
[INFO]   }
```

**Expected/desired behavior:**
No PhantomJS ERROR with __zone_symbol__currentTask.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.**
1. Create Angular 4.0.0 app with Node v6.9.1, npm 3.10.8, angular-cli 1.0.0, karma, PhantomJS.
2. Add unit tests that use promises.
3. Run unit tests.

Apologies, the exact code is proprietary. I may be able to provide a minimal demo, but I do not have one yet.

The reported error only occurs with karma-webpack@2.0.9 and not with karma-webpack@2.0.6.

* **What is the expected behavior?**
No PhantomJS ERROR with __zone_symbol__currentTask.

* **What is the motivation / use case for changing the behavior?**

**Comment by codymikol** [comment]
Going to close this as I doubt anyone is working with phantomjs / angular 4 /karma-webpack v2. If I'm wrong, please feel free to comment and I'll open this back up.
