### ISSUE TITLE
`webpackOptions.output.publicPath` should be configurable

### ISSUE THREAD

**Issue by sechel** [ryanclark/karma-webpack#337]
Hi there,

some time ago (in 0616dda489d07f6a9bc3def1778dcef601411821) you decided to switch from a static `webpackOptions.output.publicPath`, i.e., `/_karma_webpack_/...` to a dynamic, but existing on disk, temporary folder on the system.

This poses problems to my setup as I am testing `OAuth2` consent flow using the real-world endpoints. In this setup I cannot use a dynamic redirect `URLs` as the `redirect_url` has to be registered with the identity provider in advance and has to match literally.

Here is a suggestion: Why not make the value inserted before `_karma_webpack_` here 
https://github.com/webpack-contrib/karma-webpack/blob/1ac16eaa7b11ee154a2127d4f03cbfd1a81533f6/src/karma-webpack.js#L64
configurable?

Greetings
Stefan

**Comment by neben** [comment]
Has there been any progress on this?

**Comment by danielhusar** [comment]
+1 I would like to output path to be configurable as well. Would you accept PRs ?

**Comment by matthieu-foucault** [comment]
I would welcome a PR!

**Comment by sechel** [comment]
Thanks for fixing it in `4.0.0-rc.2`. 😀

**Comment by sechel** [comment]
Nevertheless would it be great to have the parameter configurable.

**Comment by codymikol** [comment]
Closing as this is possible in 5.0.0 and has unit tests to prove that the publicPath is passed along.
