### ISSUE TITLE
[4.0.0-rc.3] Bug or feature? Behavior when webpack configuration has an entry

### ISSUE THREAD

**Issue by matthieu-foucault** [ryanclark/karma-webpack#372]
Documentation Is:

- [ ] Missing
- [ ] Needed
- [ ] Confusing
- [x] Not Sure?

### The issue

In the Readme, the comments say `you don't need to specify the entry option`. It doesn't say what happens if you do though. Currently, whatever is in the configuration `entry` will be bundled by Webpack in addition to the karma `files`.
If you are like me and you are reusing the same configuration for building and testing, it makes the testing really slow, as the main entry point of your application will be bundled with the tests.

### What should be done

- If that is a feature, we need to make the documentation clearer and explain that if you do have an `entry` in the Webpack config, it will be bundled. My understanding was that it was ignored since karma uses the `files` and `preprocessors` options.

- If that is a bug, let's fix it, and also document that. Would removing the `if` statement [here](https://github.com/webpack-contrib/karma-webpack/blob/master/src/karma-webpack.js#L72) do the trick?

**Comment by rynclark** [comment]
Yes, it'll build any given entry files and also add all the given test files as entry files too. I don't think we should restrict this, as there are probably reasons that this behaviour would be wanted, but I agree that the docs could be a bit better.

**Comment by codymikol** [comment]
Currently v5 enforces a single entry point and there is another ticket out for supporting multiple entries #165
