### ISSUE TITLE
[5.0.0-alpha.3.0] Can't bundle Typescript

### ISSUE THREAD

**Issue by vcvuwac** [ryanclark/karma-webpack#423]
I'd like to use karma-webpack to compile typescript.

- Operating System: Windows 10
- Node Version: v11.9.0
- NPM Version: 6.5.0
- webpack Version: 4.35.2
- karma-webpack Version: 5.0.0-alpha.3.0

### Expected Behavior

Successfully complete test.

### Actual Behavior

```
TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be one of type string, TypedArray, or DataView. Received type undefined
    at Hash.update (internal/crypto/hash.js:64:11)
    at Object.sha1 (C:\Users\HiICS\Desktop\karmatest\node_modules\karma\lib\utils\crypto-utils.js:9:8)
    at nextPreprocessor (C:\Users\HiICS\Desktop\karmatest\node_modules\karma\lib\preprocessor.js:28:30)
    at processFile (C:\Users\HiICS\Desktop\karmatest\node_modules\karma-webpack\lib\karma-webpack.js:120:5)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
```

karma-webpack generates a name of bundle file from ```.ts``` path.
https://github.com/webpack-contrib/karma-webpack/blob/eec6dfc9e80413fe957136975034757bdffe9e8e/lib/karma-webpack.js#L84-L87

However it gets a bundle content from a file path generated from ```.js``` path.
So, second argument of ```done()``` is always ```undefined```.
https://github.com/webpack-contrib/karma-webpack/blob/eec6dfc9e80413fe957136975034757bdffe9e8e/lib/karma-webpack.js#L105-L120

### Code

```js
// karma.conf.js
module.exports = function(config) {
  config.set({
    frameworks: ['jasmine'],
    files: ['index.test.ts'],
    preprocessors: {
      '*.ts': ['webpack']
    },
    browsers: ['Chrome'],
    webpack: {
      resolve: { extensions: ['.ts'] },
      module: {
        rules: [
          { test: /\.ts$/, use: ['ts-loader'] }
        ]
      }
    }
  })
}
```

```js
// index.test.ts
describe("Test", () => it("test", () => expect(true).toBe(true)));
```

### How Do We Reproduce?

See ```karma.conf.js``` above. You can install all dependencies by ```npm i -D karma karma-chrome-launcher karma-jasmine jasmine karma-webpack@5.0.0-alpha.3.0 webpack ts-loader typescript @types/jasmine```. This bug is also reproduced if you use mocha. No problem even if ```tsconfig.json``` is an empty file.
It's not reproduced in karma-webpack@4.0.2

**Comment by naoak** [comment]
I made [a patch](https://github.com/webpack-contrib/karma-webpack/files/4500886/karma-webpack%2B5.0.0-alpha.3.0.patch.txt) for this issue. Hope this helps anyone.

**Comment by codymikol** [comment]
To limit confusion, I am combining all threads for webpack 5 / karma6 support over here ==> https://github.com/ryanclark/karma-webpack/issues/475

**Comment by codymikol** [comment]
v5 is now available
