### ISSUE TITLE
Support karma v5

### ISSUE THREAD

**Issue by limonte** [ryanclark/karma-webpack#439]
`karma` v5 has been released: https://github.com/karma-runner/karma/releases/tag/v5.0.0

The current version of `karma-webpack` doesn't seem to be compatible with karma v5, I'm getting this error:

```
ERROR [preprocess]: Can not load "webpack"!
TypeError: Cannot promisify an API that has normal methods with 'Async'-suffix
```

See breaking changes:

![image](https://user-images.githubusercontent.com/6059356/78930655-26605600-7aad-11ea-818e-0fb914bb980a.png)

**Comment by limonte** [comment]
Actually, that was the issue on `karma`'s side: https://github.com/karma-runner/karma/issues/3466

**Comment by codymikol** [comment]
I'm going to close this as it seems the issue was resolved, let me know if you're still having issues.
