### ISSUE TITLE
Webpack watches file changes in singleRun mode

### ISSUE THREAD

**Issue by shihabuddin** [ryanclark/karma-webpack#448]
- Operating System: Windows 10
- Node Version: 12.18.1
- NPM Version: 6.14.5
- webpack Version: 4.44.1
- karma-webpack Version: 4.0.2

### Expected Behavior

When `singleRun` is set to `true`, webpack dev middleware doesn't watch for file changes.

### Actual Behavior

When `singleRun` is set to `true`, webpack dev middleware watches for file changes and re-compiles them when I make changes.

### Code

https://github.com/shihabuddin/karma-webpack-watch

### How Do We Reproduce?

* Clone the above minimal repo.
* `npm ci`
* `npm test`
* While the test is running, make some changes to `test/test.js` and save.
* A `Compiling...` message from `wdm` is printed in the console.

**Comment by ryanclark** [comment]
Thank you so much for providing a reproducible repo for this issue. I'll take a look at it this week/weekend.

**Comment by shihabuddin** [comment]
I am working on creating a PR with a suggested fix.

**Comment by shihabuddin** [comment]
@ryanclark Any update on this? I have submitted a PR for this. Please let me know, if I can do anything to help merge the PR.

**Comment by SebastianStehle** [comment]
Any update on this? I am having the problem that my build server cannot handle all the watches.

I get a lot of errors like this

```
Error from chokidar (/src/app/features/rules/pages/rules/triggers): Error: ENOSPC: System limit for number of file watchers reached, watch '/src/app/features/rules/pages/rules/triggers/usage-trigger.component.scss'...
```

I can probably fix it on my server, but as an open source project it should also build without  these warnings on other servers.

is there a workaround?

**Comment by shihabuddin** [comment]
I have created a `test-v5` branch on the reproduce repo and upgraded `karma-webpack` to `v5.0.0`. I can't reproduce this issue any more.
