### ISSUE TITLE
Can't find how to get complete coverage for all source files in the docs

### ISSUE THREAD

**Issue by dietergeerts** [ryanclark/karma-webpack#487]
Documentation Is:

- [x] Missing
- [x] Needed
- [ ] Confusing
- [ ] Not Sure?

### Please Explain in Detail...

The documentation (the readme file) is missing info on how to get coverage reports on all source files, because for that, all source files need to be loaded, and the docs only show how to run your test files and load those.

### Your Proposal for Changes

Add a section on coverage in the docs, so users know how to do this.

**Comment by codymikol** [comment]
I think code coverage would be outside the scope of this plugin. Have you tried using something like https://github.com/karma-runner/karma-coverage ?

**Comment by codymikol** [comment]
Closing this, if something in karma-webpack is blocking your ability to use a coverage reporter let me know and I can open this back up.
