### ISSUE TITLE
Merging does not work, plugins get duplicated

### ISSUE THREAD

**Issue by lk77** [ryanclark/karma-webpack#496]
* Operating System: Ubuntu 18.10
* Node Version: v14.15.4
* NPM Version: 6.14.10
* webpack Version: 5.23.0
* karma-webpack Version: 5.0.0

### Expected Behavior

Plugins are only included once

### Actual Behavior

Plugins are included twice due to issue when merging webpack config

### Code

webpack config :
```
 plugins: [
        new VueLoaderPlugin()
    ],
```

webpack config after merging (this.webpackOptions)
```
 plugins: [
    VueLoaderPlugin {},
    VueLoaderPlugin {},
    KW_WebpackPlugin {
      karmaEmitter: [Server],
      controller: [KW_Controller]
    }
  ],

```

### How Do We Reproduce?

Add a plugin in your webpack config and see that this plugin is added twice

thanks

**Comment by codymikol** [comment]
Was this not an issue?

**Comment by lk77** [comment]
no it was not, an issue on my end
