### ISSUE TITLE
I have the same problem.

### ISSUE THREAD

**Issue by Dilranga98** [ryanclark/karma-webpack#541]
ERROR in ./src/config/index.js
Module not found: Error: Can't resolve './config.js' in '/home/breadcrumbs-ubuntu/Desktop/test/scdm-client/src/config'
 @ ./src/config/index.js 5:13-35
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 webpack/hot/dev-server ./src/main.js

ERROR in ./src/templates/index.js
Module not found: Error: Can't resolve '../config/config' in '/home/breadcrumbs-ubuntu/Desktop/test/scdm-client/src/templates'
 @ ./src/templates/index.js 1:13-40
 @ ./src/config/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 webpack/hot/dev-server ./src/main.js

**Comment by codymikol** [comment]
I need more context to help you
