### ISSUE TITLE
preprocessor change between v4 & v5 leading to error when used with karma-mocha

### ISSUE THREAD

**Issue by subodhkumar** [ryanclark/karma-webpack#543]
* Operating System: MacOS
* Node Version: 14
* NPM Version: 6
* webpack Version: 5
* karma-webpack Version: 5

### Expected Behavior
karma-webpack should work well with karma-mocha

### Actual Behavior
This is related to executing the functional tests with `karma`,`karma-webpack` & `karma-mocha`

* we use `karma-mocha` v2. Which has the following [code](https://github.com/karma-runner/karma-mocha/blob/537ef7bafb2a1c78c32ba9d54ca3bef877c52c34/lib/index.js#L11) to add files to existing fileList passed to webpack plugin
* in `karma-webpack` v4, the preprocessor had the [code](https://github.com/ryanclark/karma-webpack/blob/2cc549531cb03f9dbb84fd4946050a8d4db5208a/src/karma-webpack.js#L396) to include files which were not part of `entryPoints` & compile them & make it available.
* in `karma-webpack` v5, the preprocessor [code](https://github.com/ryanclark/karma-webpack/blob/e2423b47ec59059bc1808c670affa64d0f5aa8b7/lib/karma-webpack/preprocessor.js#L87) is changed to skip the inclusion of files & just includes the entryPoints for compilation.

In our usecase where we recently updated the `karma-webpack`, we are facing errors as few files are not available post preprocessing causing the karma server to fail.

Not sure if the change is a bug or intended. Just wanted to understand the reason behind the change. Appreciate if there are any workarounds & corrections in my understanding of the code.

**Comment by codymikol** [comment]
In v5 you can require all of the files you want to include in your entry point rather than pass them in via configuration. Let me know if that works for you.

**Comment by subodhkumar** [comment]
Thanks for the response. In our use case we have set all the entrypoints.

however as shared above karma-mocha is adding few files which is not configured by us. With v5 as karma-webpack as it’s not adding files in the preprocessor those files are part of bundle output causing the error. 

Are you recommending to import the files added by karma-mocha by us explicitly.

**Comment by codymikol** [comment]
What files is karma-mocha adding?

**Comment by codymikol** [comment]
> Are you recommending to import(set in the entry section) the files added by karma-mocha by us explicitly.

If you mean these files are created by you and added in your mocha config, yes, this should fix your problem.

**Comment by subodhkumar** [comment]
> Which files are karma-mocha adding?

karma-mocha is adding `karma-mocha/src/adapter.js`

**Comment by subodhkumar** [comment]
> > Are you recommending to import(set in the entry section) the files added by karma-mocha by us explicitly.
> 
> If you mean these files are created by you and added in your mocha config, yes, this should fix your problem.

the files are not created by us, but are added by `karma-mocha`. These files used to be picked up by karma-webpack v4 [here](https://github.com/ryanclark/karma-webpack/blob/2cc549531cb03f9dbb84fd4946050a8d4db5208a/src/karma-webpack.js#L396).

**Comment by codymikol** [comment]
Can you post the error that you're getting and configs for webpack / karma / mocha? We have integration tests for karma-mocha so I know its possible to use in v5.

**Comment by subodhkumar** [comment]
Hi @codymikol,

In our project, we construct a `customTest.js` at the root level of project which has import to all the test-entry points for the project. We trigger the karma process from the root level on the `customTest.js`. In our `karma.config.js` we have the following entry of `preprocessor` 

```
preprocessors: {'**/*.js': ['webpack']}, // include add JS files from project root
```

I checked the integration tests in `karma-webpack` & checked how its working. I was able to simulate the error we are facing by making changes to one of the tests(link to the forked [karma-webpack project](https://github.com/subodhkumar/karma-webpack) with the code changes: [#1](https://github.com/subodhkumar/karma-webpack/blob/be0505c5b65427d338fa23c2f3d09404380d4175/test/integration/scenarios/basic-setup/basic-exclude.test.js#L26), [#2](https://github.com/subodhkumar/karma-webpack/blob/be0505c5b65427d338fa23c2f3d09404380d4175/test/integration/scenarios/basic-setup/basic-exclude.test.js#L32))

I have updated the `preprocessor` entries to point to the root location of the project as we have in our project. If you could clone the forked project & execute `npm run test` you will see the below error which we are getting.

![Screenshot 2022-11-28 at 12 07 36 PM](https://user-images.githubusercontent.com/5250542/204211594-3679e36d-b1d0-425f-b01b-2cd9629f173a.png)

This error is thrown as the `js` files([#file1](https://github.com/karma-runner/karma-mocha/blob/537ef7bafb2a1c78c32ba9d54ca3bef877c52c34/lib/index.js#L11), [#file2](https://github.com/karma-runner/karma-mocha/blob/537ef7bafb2a1c78c32ba9d54ca3bef877c52c34/lib/index.js#L23)) added by `karma-mocha` as allowed to be processed by the `karma-webpack` plugin due to the updated `preprocessor` pattern in karma config. However, with v5 the plugin is [not allowing](https://github.com/ryanclark/karma-webpack/blob/e2423b47ec59059bc1808c670affa64d0f5aa8b7/lib/karma-webpack/preprocessor.js#L87) any [new file additions](https://github.com/ryanclark/karma-webpack/blob/2cc549531cb03f9dbb84fd4946050a8d4db5208a/src/karma-webpack.js#L396) as compared to v4.

As the plugin is skipping the files added by `karma-mocha`(or plugin which might have similar code) the [following code](https://github.com/karma-runner/karma/blob/50f963551fbccf669c8d42499d0406ded2ec6176/lib/preprocessor.js#L68-L70) in `karma` is finding empty content for files added by `karma-mocha` & causing the error while setting `sha1` to `undefined`

Hope this conveys the issue.

I have the below followup queries.
* Is setting the `preprocessor` path at the root level a valid entry?
* if Yes, should this error be a bug?
* If No, `karma-webpack` v4 used to allow it. Should this change in option be documented.

Thanks again for your time in checking & responding. Really appreciate it.

**Comment by codymikol** [comment]
This is trying to run the webpack preprocessor on all files in the repository including node_modules via globbing, try using a single file that specifies exactly what you want to import like the index.scenario.js file.

**Comment by subodhkumar** [comment]
So is including the files on node_modules as part of preprocessor pattern invalid?
If so, this used to work in karma-we pack v4. Also, any reason for removing add files code in v5

**Comment by codymikol** [comment]
Can you share your project or at least configurations? I may be able to point you in the right direction.

**Comment by subodhkumar** [comment]
Updated the preprocessor pattern to include only test files to address the issue we faced. Thanks for the support
