### ISSUE TITLE
Karma doesn't fail on jsxhint-loader failure

### ISSUE THREAD

**Issue by melbarra88** [ryanclark/karma-webpack#94]
Hi,

I am trying to make my dev process fail fast on jsxhint error because there is no need to run tests when script doesn't satisfies jsxhint. 

I am using jsxhint-laoder as a preLoader. when built directly with webpack, the jsxhint errors make build fail, but with  karma-webpack, It doesn't prevent tests from running on error.

here is my jsxhint-loader : 

``` javascript
module.exports = {
    ...
    module: {
        preLoaders: [
            {
                test: /\.js.?$/,
                exclude: [/node_modules/, /vendor/],
                loader: "jsxhint-loader"
            }
        ],
      loaders: [ ... ]
    },
     jshint: {
        emitErrors: true,
        failOnHint: true
    }
};
```

How can I make my dev process fail fast? 
Thanks in advance.

**Comment by goldhand** [comment]
I think this might be related to #66

**Comment by codymikol** [comment]
Closing due to the age of this ticket, if you're still having issues with the current build feel free to open a new ticket with the relevant information and I'll help as best I can!
